@baseUrl = http://localhost:3004
@contentType = application/json

### Get all URLs
GET {{baseUrl}}/api/urls

### Shorten a URL
POST {{baseUrl}}/api/shorten
Content-Type: application/json

{
  "url": "https://stackoverflow.com/"
}

### Redirect to Original URL (if found)
GET {{baseUrl}}/test
